let contador = 0;


const actualizarContador = () => {

    contador++;
    const elemContador = document.getElementById('contador');
    elemContador.innerHTML = contador;

}


const url = 'https://pre.ifacturatransfiriendo.transfiriendo.com/DianV2WCF/FacturaService.svc';

let data = `<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <UserName>administradorti</UserName>
        <Password>!QAZxsw2ZLÑ</Password>
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <generarDocumento xmlns="http://tempuri.org/">
            <documentoElectronico xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                <documento>
                    <identificadorTransaccion>94d8f9e2-6bea-47c4-9ea9-26c410ba902f</identificadorTransaccion>
                    <NITFacturador>900482242</NITFacturador>
                    <prefijo>SM</prefijo>
                    <numeroDocumento>18330</numeroDocumento>
                    <tipoDocumento>1</tipoDocumento>
                    <subTipoDocumento>01</subTipoDocumento>
                    <tipoOperacion>SS-CUFE</tipoOperacion>
                    <plantilla>2</plantilla>
                    <generaRepresentacionGrafica>true</generaRepresentacionGrafica>
                    <fechaEmision>2022-03-19</fechaEmision>
                    <horaEmision>09:57:03-05:00</horaEmision>
                    <fechaVencimiento>2022-04-18</fechaVencimiento>
                    <fechaInicioPeriodo>2022-03-03</fechaInicioPeriodo>
                    <horaInicioPeriodo>09:10:06-05:00</horaInicioPeriodo>
                    <fechaFinPeriodo>2022-03-03</fechaFinPeriodo>
                    <horaFinPeriodo>10:10:06-05:00</horaFinPeriodo>
                    <moneda>COP</moneda>
                    <codigoCentroCostos>CHSM</codigoCentroCostos>
                    <contactoEntrega>
                        <nombre>CLAUDIA POSSE VELASQUEZ</nombre>
                    </contactoEntrega>
                    <notificaciones>
                        <notificacion>
                            <tipo>1</tipo>
                            <valor>
                                <string>RECEPCIONCUENTASMEDICAS@COLMEDICA.COM</string>
                            </valor>
                        </notificacion>
                    </notificaciones>
                    <formaPago>
                        <tipoPago>2</tipoPago>
                        <codigoMedio>ZZZ</codigoMedio>
                        <fechaVencimiento>2022-03-19</fechaVencimiento>
                    </formaPago>
                    <informacionesAdicionales>
                        <informacionAdicional>
                            <nombre>CodigoHabitacion</nombre>
                            <valor>130010332101</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>valoraPagar</nombre>
                            <valor>449186</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NumeroIngreso</nombre>
                            <valor>2203000504</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>CodigoAsistenciaComplementaria</nombre>
                            <valor>130010332101</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NumeroAutorizacion</nombre>
                            <valor>(221-25280520|2022-03-03||)</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>TipoDocumentoPaciente</nombre>
                            <valor>13</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NumeroDocumentoPaciente</nombre>
                            <valor>22613251</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>PrimerNombrePaciente</nombre>
                            <valor>BRIANA</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>SegundoNombrePaciente</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>PrimerApellidoPaciente</nombre>
                            <valor>ROMERO</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>SegundoApellidoPaciente</nombre>
                            <valor>AVILA</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>FechaNacimientoPaciente</nombre>
                            <valor>1980-04-22</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>TipoAfiliacionPaciente</nombre>
                            <valor>1</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>EdadPaciente</nombre>
                            <valor>42</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>SexoPaciente</nombre>
                            <valor>F</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>EsMultipaciente</nombre>
                            <valor>FALSE</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>TipoServicio</nombre>
                            <valor>3</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NumeroAtencionConvenio</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>CodigoMedico</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>DiasEstancia</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>DiagnosticoIngreso</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>DiagnosticoEgreso</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>SociedadMedica</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>PolizaAtencion</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>PolizaAtencionAseguradora</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NumeroHistoria</nombre>
                            <valor>22613251</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>CodigoConvenio</nombre>
                            <valor>22</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>CodigoFacturador</nombre>
                            <valor>SMA49952</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>TipoDocumentoFacturador</nombre>
                            <valor>13</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NumeroDocumentoFacturador</nombre>
                            <valor>1047449952</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>NombreFacturador</nombre>
                            <valor>EDUARDO</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>ApellidoFacturador</nombre>
                            <valor>LUIS GOMEZ GONZALEZ</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>Idpacienteconvenio</nombre>
                            <valor>22</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>ObservacionesFactura</nombre>
                            <valor></valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>TotalFacturaDolares</nombre>
                            <valor>0</valor>
                        </informacionAdicional>
                        <informacionAdicional>
                            <nombre>TotalFacturaDolaresMoneda</nombre>
                            <valor></valor>
                        </informacionAdicional>
                    </informacionesAdicionales>
                    <extensionesSalud>
                        <extensionSalud>
                            <codigoPrestador>130010332101</codigoPrestador>
                            <tipoDocumentoIdentificacion>CC</tipoDocumentoIdentificacion>
                            <numeroIdentificacion>22613251</numeroIdentificacion>
                            <primerApellido>ROMERO</primerApellido>
                            <segundoApellido>AVILA</segundoApellido>
                            <primerNombre>BRIANA</primerNombre>
                            <tipoDeUsuario>CONTRIBUTIVO BENEFICIARIO</tipoDeUsuario>
                            <modalidadesContratacion>POR SERVICIO</modalidadesContratacion>
                            <cobertura>COBERTURA RÉGIMEN ESPECIAL O EXCEPCIÓN</cobertura>
                            <numeroAutorizacion>
                                <string>221-25280520</string>
                            </numeroAutorizacion>
                            <fechaInicioFacturacion>2022-03-03</fechaInicioFacturacion>
                            <fechaFinFacturacion>2022-03-03</fechaFinFacturacion>
                            <copago>0</copago>
                            <cuotaModeradora>0</cuotaModeradora>
                            <cuotaRecuperacion>0</cuotaRecuperacion>
                            <pagosCompartidos>0</pagosCompartidos>
                        </extensionSalud>
                    </extensionesSalud>
                </documento>
                <adquiriente>
                    <identificacion>800106339</identificacion>
                    <tipoIdentificacion>31</tipoIdentificacion>
                    <codigoInterno>22</codigoInterno>
                    <matriculaMercantil>0</matriculaMercantil>
                    <razonSocial>COLMEDICA - PIEDRAS PRECIOSAS</razonSocial>
                    <nombreSucursal>BOGOTA D.C.-FONTIBON</nombreSucursal>
                    <correo>RECEPCIONCUENTASMEDICAS@COLMEDICA.COM</correo>
                    <telefono>3240250 -</telefono>
                    <sitio>RECEPCIONCUENTASMEDICAS@COLMEDICA.COM</sitio>
                    <responsabilidadesRUT>
                        <string>O-13</string>
                    </responsabilidadesRUT>
                    <tipoPersona>1</tipoPersona>
                    <ubicacion>
                        <pais>CO</pais>
                        <codigoMunicipio>11001</codigoMunicipio>
                        <ciudad></ciudad>
                        <departamento>BOGOTA D.C.</departamento>
                        <direccion>AVENIDA EL DORADO 69C - 03</direccion>
                    </ubicacion>
                </adquiriente>
                <cargosDescuentos>
                    <cargoDescuento>
                        <esCargo>false</esCargo>
                        <codigo>01</codigo>
                        <valorImporte>0</valorImporte>
                        <valorImporteMoneda>COP</valorImporteMoneda>
                        <valorBase>0</valorBase>
                        <valorBaseMoneda>COP</valorBaseMoneda>
                        <porcentaje>0</porcentaje>
                    </cargoDescuento>
                </cargosDescuentos>
                <tributos>
                    <tributo>
                        <id>01</id>
                        <nombre>IVA</nombre>
                        <esImpuesto>false</esImpuesto>
                        <valorImporteTotal>0</valorImporteTotal>
                        <valorImporteTotalMoneda>COP</valorImporteTotalMoneda>
                        <detalles>
                            <tributoDetalle>
                                <valorImporte>0</valorImporte>
                                <valorImporteMoneda>COP</valorImporteMoneda>
                                <valorBase>449186</valorBase>
                                <valorBaseMoneda>COP</valorBaseMoneda>
                                <porcentaje>0</porcentaje>
                                <tributoFijoUnidades>0</tributoFijoUnidades>
                                <tributoFijoValorImporte>0</tributoFijoValorImporte>
                            </tributoDetalle>
                        </detalles>
                    </tributo>
                </tributos>
                <totales>
                    <valorBruto>449186</valorBruto>
                    <valorBrutoMoneda>COP</valorBrutoMoneda>
                    <valorCargos>0</valorCargos>
                    <valorCargosMoneda>COP</valorCargosMoneda>
                    <valorDescuentos>0</valorDescuentos>
                    <valorDescuentosMoneda>COP</valorDescuentosMoneda>
                    <valorAnticipos>0</valorAnticipos>
                    <valorAnticiposMoneda>COP</valorAnticiposMoneda>
                    <valorRedondeo>0</valorRedondeo>
                    <valorRedondeoMoneda>COP</valorRedondeoMoneda>
                    <valorTotalSinImpuestos>449186</valorTotalSinImpuestos>
                    <valorTotalSinImpuestosMoneda>COP</valorTotalSinImpuestosMoneda>
                    <valorTotalConImpuestos>449186</valorTotalConImpuestos>
                    <valorTotalConImpuestosMoneda>COP</valorTotalConImpuestosMoneda>
                    <valorNeto>449186</valorNeto>
                    <valorNetoMoneda>COP</valorNetoMoneda>
                </totales>
                <detalles>
                    <detalle>
                        <tipoDetalle>2</tipoDetalle>
                        <valorCodigoInterno>17</valorCodigoInterno>
                        <codigoEstandar>999</codigoEstandar>
                        <valorCodigoEstandar>17</valorCodigoEstandar>
                        <descripcion>MEDICAMENTOS</descripcion>
                        <unidades>1</unidades>
                        <unidadMedida>ZZ</unidadMedida>
                        <unidadesPorEmpaque>0</unidadesPorEmpaque>
                        <valorUnitarioBruto>129458</valorUnitarioBruto>
                        <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                        <valorBruto>129458</valorBruto>
                        <valorBrutoMoneda>COP</valorBrutoMoneda>
                        <valorReferencia>0</valorReferencia>
                        <informacionesAdicionales>
                            <informacionAdicional>
                                <nombre>Codigo</nombre>
                                <valor>999</valor>
                            </informacionAdicional>
                            <informacionAdicional>
                                <nombre>ValorUnitarioOtraDivisa</nombre>
                                <valor>0</valor>
                            </informacionAdicional>
                            <informacionAdicional>
                                <nombre>MonedaOtraDivisa</nombre>
                                <valor>USD</valor>
                            </informacionAdicional>
                        </informacionesAdicionales>
                        <subDetalles>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1141011120</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1141011120</valorCodigoEstandar>
                                <descripcion>* IOVERSOL X 320MG/ML SOLUCION INYECTABLE JERINGA INYECTOR X 75ML</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>48968</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>48968</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>48968</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>48968</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1141013063</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1141013063</valorCodigoEstandar>
                                <descripcion>SULFATO DE BARIO X 10G (4,9%) SUSPENSION ORAL FRASCO X 225ML</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>80490</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>80490</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>80490</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>80490</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                        </subDetalles>
                    </detalle>
                    <detalle>
                        <tipoDetalle>2</tipoDetalle>
                        <valorCodigoInterno>203</valorCodigoInterno>
                        <codigoEstandar>999</codigoEstandar>
                        <valorCodigoEstandar>203</valorCodigoEstandar>
                        <descripcion>IMAGENOLOGIA</descripcion>
                        <unidades>1</unidades>
                        <unidadMedida>ZZ</unidadMedida>
                        <unidadesPorEmpaque>0</unidadesPorEmpaque>
                        <valorUnitarioBruto>283297</valorUnitarioBruto>
                        <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                        <valorBruto>283297</valorBruto>
                        <valorBrutoMoneda>COP</valorBrutoMoneda>
                        <valorReferencia>0</valorReferencia>
                        <informacionesAdicionales>
                            <informacionAdicional>
                                <nombre>Codigo</nombre>
                                <valor>999</valor>
                            </informacionAdicional>
                            <informacionAdicional>
                                <nombre>ValorUnitarioOtraDivisa</nombre>
                                <valor>0</valor>
                            </informacionAdicional>
                            <informacionAdicional>
                                <nombre>MonedaOtraDivisa</nombre>
                                <valor>USD</valor>
                            </informacionAdicional>
                        </informacionesAdicionales>
                        <subDetalles>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>879420</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>879420</valorCodigoEstandar>
                                <descripcion>TOMOGRAFIA COMPUTADA DE ABDOMEN Y PELVIS (ABDOMEN TOTAL)</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>283297</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>283297</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>283297</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>283297</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                        </subDetalles>
                    </detalle>
                    <detalle>
                        <tipoDetalle>2</tipoDetalle>
                        <valorCodigoInterno>16</valorCodigoInterno>
                        <codigoEstandar>999</codigoEstandar>
                        <valorCodigoEstandar>16</valorCodigoEstandar>
                        <descripcion>INSUMOS</descripcion>
                        <unidades>1</unidades>
                        <unidadMedida>ZZ</unidadMedida>
                        <unidadesPorEmpaque>0</unidadesPorEmpaque>
                        <valorUnitarioBruto>36431</valorUnitarioBruto>
                        <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                        <valorBruto>36431</valorBruto>
                        <valorBrutoMoneda>COP</valorBrutoMoneda>
                        <valorReferencia>0</valorReferencia>
                        <informacionesAdicionales>
                            <informacionAdicional>
                                <nombre>Codigo</nombre>
                                <valor>999</valor>
                            </informacionAdicional>
                            <informacionAdicional>
                                <nombre>ValorUnitarioOtraDivisa</nombre>
                                <valor>0</valor>
                            </informacionAdicional>
                            <informacionAdicional>
                                <nombre>MonedaOtraDivisa</nombre>
                                <valor>USD</valor>
                            </informacionAdicional>
                        </informacionesAdicionales>
                        <subDetalles>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1210010111</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1210010111</valorCodigoEstandar>
                                <descripcion>GASA IMPREGNADA CON ALCOHOL 70%</descripcion>
                                <unidades>2</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>99</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>198</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>198</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>198</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1221010018</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1221010018</valorCodigoEstandar>
                                <descripcion>EQUIPO DE VENOCLISIS S/AGUJA (MACROGOTEO)</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>1488</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>1488</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>1488</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>1488</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1203010408</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1203010408</valorCodigoEstandar>
                                <descripcion>EXTENSION EN Y CON VALVULA ANTIREFLUJO CASE 60" Y TUBO REF:844012</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>23048</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>23048</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>23048</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>23048</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1201010038</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1201010038</valorCodigoEstandar>
                                <descripcion>CATETER INTRAVENOSO 20GX 1 1/4" AUTOGUARD</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>5000</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>5000</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>5000</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>5000</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1221040013</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1221040013</valorCodigoEstandar>
                                <descripcion>EXTENSION PARA ANESTESIA ADULTO</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>1248</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>1248</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>1248</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>1248</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1149011039</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1149011039</valorCodigoEstandar>
                                <descripcion>SOLUCION SALINA X 0,9% SOLUCION INYECTABLE BOLSA X 250ML X UND</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>2760</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>2760</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>2760</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>2760</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                            <subDetalle>
                                <tipoDetalle>1</tipoDetalle>
                                <valorCodigoInterno>1211010172</valorCodigoInterno>
                                <codigoEstandar>999</codigoEstandar>
                                <valorCodigoEstandar>1211010172</valorCodigoEstandar>
                                <descripcion>JERINGA PRELLENADA CON SOLUCION SALINA 0.9% 10ML/10CC REF.306565</descripcion>
                                <unidades>1</unidades>
                                <unidadMedida>ZZ</unidadMedida>
                                <unidadesPorEmpaque>0</unidadesPorEmpaque>
                                <valorUnitarioBruto>2689</valorUnitarioBruto>
                                <valorUnitarioBrutoMoneda>COP</valorUnitarioBrutoMoneda>
                                <valorBruto>2689</valorBruto>
                                <valorBrutoMoneda>COP</valorBrutoMoneda>
                                <valorReferencia>0</valorReferencia>
                                <tributos>
                                    <detalleTributo>
                                        <id>01</id>
                                        <nombre>IVA</nombre>
                                        <esImpuesto>false</esImpuesto>
                                        <valorImporte>0</valorImporte>
                                        <valorImporteMoneda>COP</valorImporteMoneda>
                                        <valorBase>2689</valorBase>
                                        <valorBaseMoneda>COP</valorBaseMoneda>
                                        <porcentaje>0</porcentaje>
                                        <tributoFijoUnidades>0</tributoFijoUnidades>
                                        <tributoFijoValorImporte>0</tributoFijoValorImporte>
                                    </detalleTributo>
                                </tributos>
                                <informacionesAdicionales>
                                    <informacionAdicional>
                                        <nombre>FechaPrestacion</nombre>
                                        <valor>2022-03-03</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TipoDocumentoPaciente</nombre>
                                        <valor>13</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroDocumentoPaciente</nombre>
                                        <valor>22613251</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerNombrePaciente</nombre>
                                        <valor>BRIANA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoNombrePaciente</nombre>
                                        <valor></valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>PrimerApellidoPaciente</nombre>
                                        <valor>ROMERO</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>SegundoApellidoPaciente</nombre>
                                        <valor>AVILA</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>TarifaContratada</nombre>
                                        <valor>2689</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValidarTarifaContratada</nombre>
                                        <valor>FALSE</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroAutorizacion</nombre>
                                        <valor>(221-25280520|2022-03-03||)</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngreso</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>NumeroIngresoDAU</nombre>
                                        <valor>2203000504</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>ValorUnitarioOtraDivisa</nombre>
                                        <valor>0</valor>
                                    </informacionAdicional>
                                    <informacionAdicional>
                                        <nombre>MonedaOtraDivisa</nombre>
                                        <valor>USD</valor>
                                    </informacionAdicional>
                                </informacionesAdicionales>
                            </subDetalle>
                        </subDetalles>
                    </detalle>
                </detalles>
            </documentoElectronico>
        </generarDocumento>
    </s:Body>
</s:Envelope>`;

const parser = new DOMParser();
xmlDoc = parser.parseFromString(data,"text/xml");

var request = new Request(url, {
	method: 'POST',
	body: xmlDoc,
    mode: 'no-cors',
	headers: {
        'Content-type': 'application/xml'
    },

});

console.log(xmlDoc);

fetch(request)
.then( response => {
    console.log(response);
}).catch ( error => {
    console.log(error)
});

